#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

path=(/Users/nm/.krew/bin $path)
fpath=(/Users/nm/.granted/zsh_autocomplete/assume/ $fpath)
fpath=(/Users/nm/.granted/zsh_autocomplete/granted/ $fpath)
